### ISSUE TITLE
BoneMatrix request

### ISSUE THREAD

**Issue by mshooter** [scripthookvdotnet/scripthookvdotnet#1078]
**Version**
scripthookvdotnet3.4.0

**Description**
I was wondering if there was a way to access the boneMatrix (transformation matrix of the bone) ? 
Thank you :)

**Comment by kagikn** [comment]
I need to find if there is any way to access the boneMatrix before I can decide if I should put enhancement tags. I don't think this issue is created for bugs, though.

**Comment by mshooter** [comment]
No sorry it wasn’t meant to be a bug. 
i put the the tag by accident and didn’t know how to delete it. 
i was wondering if the bone matrix basically gives the world transformation matrix of the bone?

**Comment by kagikn** [comment]
Maybe `PoseMatrix` or `RelativeMatrix` of `EntityBone` could help, but I’m not sure how they work actually. I haven’t used none of them or changed code about them.
I guess it’s good chance to test them and write documentation more, but I need some time to figure out how the properties work.

**Comment by mshooter** [comment]
Ok that’s alright thank you !

**Comment by kagikn** [comment]
#1211 fulfills what this issue is for I guess?
