### ISSUE TITLE
Add more arguments to Tasks in Ped.Task

### ISSUE THREAD

**Issue by m3nd3zz** [scripthookvdotnet/scripthookvdotnet#1231]
Just a simple feature. Add more arguments to tasks in `Ped.Task`. Example
![image](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/133176408/4454a5c9-2350-4a80-8901-328a7b9292da)
The two arguments inside the red circle can't be changed unless the script call from the native task.
That would be helpful to TaskSequence, because you wouldn't need to call the native task just to add more arguments

**Comment by kagikn** [comment]
Ah, you must be Mendez who I helped for `TaskSequence` in the Discord server of Lemon a few days ago.

I also added more notes to `TaskInvoker.WanderAround` and `TaskSequence` in 9ef6123 and 3e88ad6 so you and other script devs can know the potential pitfalls.

**Comment by m3nd3zz** [comment]
> Ah, you must be Mendez who I helped for `TaskSequence` in the Discord server of Lemon a few days ago.
> 
> I also added more notes to `TaskInvoker.WanderAround` and `TaskSequence` in [9ef6123](https://github.com/scripthookvdotnet/scripthookvdotnet/commit/9ef61238ec46cb53969a2102fac6fdda59490d6c) and [3e88ad6](https://github.com/scripthookvdotnet/scripthookvdotnet/commit/3e88ad61e31b0be4b3120fcf0da9901be75953e2) so you and other script devs can know the potential pitfalls.

Thanks.
I am new at this GitHub thing, don't know how exactly everthing works
