### ISSUE TITLE
Any solution to change  GameplayCamera position and rotation?

### ISSUE THREAD

**Issue by ILaCHu** [scripthookvdotnet/scripthookvdotnet#1269]
Will be very useful to add this options... Thx.
 May be  get some info  out from https://github.com/CamxxCore/ExtendedCameraSettings/blob/master/src/main.cpp ???

**Comment by kagikn** [comment]
No hope I believe. I tried changing the vector3 value for the position at `[camGameplayDirector + 0x220]`, where `GET_GAMEPLAY_CAM_COORD` reads, but the change didn't applied. Some cam function overwrites the member with another pos value of another `camFrame` instance.

**Comment by ILaCHu** [comment]
One more question, I try experimented with bone.Pose and PoseRotation. I using SET_PED_CAN_ARM_IK to enable it. So if I create custom camera and try change value nothing to change  in Gameplay First Person Cam all is O'key.  Can I  in custom Camera using   SET_PED_CAN_ARM_IK  too?

**Comment by kagikn** [comment]
I would say your second question doesn't make enough sense to me due to the grammar, but we should discuss it in [the Discussions page](https://github.com/scripthookvdotnet/scripthookvdotnet/discussions) or another issue if you want to do so other people can find easily.
