### ISSUE TITLE
Gta.Vehicleseat

### ISSUE THREAD

**Issue by Niklas20** [scripthookvdotnet/scripthookvdotnet#1322]
would it be possible to add some automatic search thing to gta.vehicleseat so it would search automatically a free seat in car and put a ped to the free seat? and prioritize it so it would firstly check driver and then passenger.

**Comment by kagikn** [comment]
You can define a custom method in your script, like how the example below does. I'm not convinced of if implementing such method in SHVDN would really worth it.
```cs
static void PutPedIntoSeat(Ped ped, Vehicle vehicle, IEnumerable<VehicleSeat> seatSearchOrder)
// assuming the ped is not in a vehicle
foreach (VehicleSeat seat in seatSearchOrder)
{
    if (vehicle.IsSeatFree(seat))
    {
        ped.SetIntoVehicle(vehicle, seat)
        break;
    }
}
```

**Comment by Niklas20** [comment]
yeah true but thanks for the code!
