### ISSUE TITLE
Provide official nightly releases that don't require GitHub account to download

### ISSUE THREAD

**Issue by kagikn** [scripthookvdotnet/scripthookvdotnet#1340]
Well, a large amount of people who use RAGE Plugin Hook really want a release with the fixes for the compatibility issue between RPH (See #976 for details). Even official nightly releases that don't require a GitHub account to download would make them happier. That will let more SHVDN script devs try new (but may be not too stable) features more easily, too. Again, I would advice against using new APIs that aren't any stable versions in production btw, because they are subject to have breaking changes.

**Comment by Variapolis** [comment]
I found this [GitHub Action](https://github.com/marketplace/actions/auto-release) that may be useful. One method could be to have a release branch and a nightly branch and when you pull into those branches, you could automatically generate a release using the GitHub Actions? I believe this should be free for a public repository. And this is one.

**Comment by kagikn** [comment]
@Variapolis Thank you for suggesting the GitHub Action, but I think we could use our procedures using [ncipollo/release-action](https://github.com/ncipollo/release-action). Also, I'd like to push nightly releases on a dedicated repo so pushing nightly releases won't notify script developers and users who aren't interested in nightly releases.

**Comment by Variapolis** [comment]
Sounds good! I think a secondary repo would be nice, as long as people have a permanent link somewhere, as currently the artifacts being temporary makes it harder for regular people with issues to download them!

**Comment by justalemon** [comment]
As an extra suggestion, can a nightly link be added to https://scripthookvdotnet.github.io ?

**Comment by kagikn** [comment]
Yeah, I think we could fetch release assets and have our website show builds for both variants even. Look at [how Ryujinx's website shows the latest release in the download page](https://ryujinx.org/download) using GitHub API (inspect the page, reload it, and watch).
