### ISSUE TITLE
Ability to add or subtract GameClockDateTime structs?

### ISSUE THREAD

**Issue by nomakewan** [scripthookvdotnet/scripthookvdotnet#1342]
I've begun the refactor for BTTFV and FusionLibrary so that we can migrate to the new GameClockDateTime structs. So far there haven't been any massive roadblocks, but there is a QOL addition that would be nice to have, which would be the ability to directly add or subtract two GameClockDateTimes from one another.

This is used, for example, to get the total number of days between two GameClockDateTimes. System.DateTime had a way to do this directly without using System.TimeSpan, so I'm wondering if it would be possible to implement for GameClockDateTime as well.

Thank you so much!

**Comment by kagikn** [comment]
I agree that `GameClockDate`, `GameClockTime`, and `GameClockDateTime` should have the subtraction operators and the static sub methods, and will implement them soon. I wonder what I forgot to implement and actually forgot them 😇
Although [`Sub<NaiveDateTime>` for `NaiveDateTime` just returns what the `signed_suration_since` returns](https://github.com/chronotope/chrono/blob/a44142528eb8bab32f9e16cb74e84bb060f4a667/src/naive/datetime/mod.rs#L1835-L1842), I admit that the absent of the sub operator makes the structs more inconvenient (the Sub trait in Rust is used for the `-` operator btw).

Addition of them doesn't make sense, however (`System.DateTime` doesn't have one either).
