### ISSUE TITLE
[Minor]: Missing ZoneID Enum and GetZoneName return value (code included)

### ISSUE THREAD

**Issue by UnknownExplorer13** [scripthookvdotnet/scripthookvdotnet#1356]
### What modules are you seeing the problem on?

ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

b440821

### Game Version

v1.0.3028.0

### Bug Description

I don't know if the V2 scripts are still being updated but they're missing the observatory ZoneID and its return value when `World.GetZoneName()` is called. Calling `Game.GetGXTEntry("OBSERV")` returns the correct value `Galileo Observatory`.

Not sure how to work pull requests but here's the file links and the code for you:
- [ZoneID.cs](https://github.com/scripthookvdotnet/scripthookvdotnet/blob/main/source/scripting_v2/GTA/ZoneID.cs)
-- `OBSERV,`
- [World.cs](https://github.com/scripthookvdotnet/scripthookvdotnet/blob/main/source/scripting_v2/GTA/World.cs#L1222)
-- `case ZoneID.OBSERV: return "Galileo Observatory";`

### Steps To Reproduce

1. Call `World.GetZoneName(Game.Player.Character.Position)` when standing at the observatory
2. Returns a blank value

### The Current Behavior

`World.GetZoneName()` returns a blank value when `OBSERV` is passed to the ZoneID switch.

### The Expected Behavior

`World.GetZoneName()` should return the zone's name as a localized string.

**Comment by kagikn** [comment]
We do address inconsistency issues when we found ones, even in v2 API 😎
