### ISSUE TITLE
Wiki outdated

### ISSUE THREAD

**Issue by Michael21107** [scripthookvdotnet/scripthookvdotnet#1363]
[INI options guide](https://github.com/scripthookvdotnet/scripthookvdotnet/wiki/User-Guides#available-options) is outdated, missing the warn of deprecated scripts and still having option to choose folder

**Comment by kagikn** [comment]
I haven't updated on purpose, but I'll update when v3.7.0 is released. Let me know if I forgot to update like 3 days after v3.7.0 is released though 😛
