### ISSUE TITLE
Deprecated scripts message clips in other text

### ISSUE THREAD

**Issue by Michael21107** [scripthookvdotnet/scripthookvdotnet#1364]
![image](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/121039033/7e0cfb61-cbaf-4bdb-8b46-7be2b0e53920)

**Comment by kagikn** [comment]
known issue, mentioned in #1301. Just wait until I create a PR for it. I'm refactoring a lot of the codebase, but I'll create before releasing v3.7.0.

**Comment by Michael21107** [comment]
gotcha, and sorry for not checking it
