### ISSUE TITLE
Install instructions for stable release

### ISSUE THREAD

**Issue by Michael21107** [scripthookvdotnet/scripthookvdotnet#1377]
release an update for 3.6.0 that will only update readme so people who got a link directly to the release page or got the copy from another source (as that's allowed under the license) will know how to install it

**Comment by kagikn** [comment]
Nah, I'm not convinced of how much an update where only the readme differs is worth. I haven't seen many people struggling which file they should place. Also, changing an release would also change what hash functions such as SHA ones will produce and you would have to calculate again to see if archive files are the ones you are supposed to download.

**Comment by Michael21107** [comment]
gotcha, just a thougt
