### ISSUE TITLE
[Bug]: Steering Angle value of Vehicle class does not change

### ISSUE THREAD

**Issue by QuestDragon** [scripthookvdotnet/scripthookvdotnet#1398]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

b5a25a8 

### Game Version

v1.0.3095.0

### Bug Description

I wanted to use the value of the **Vehicle class** attribute **Steering Angle** to know the steering angle of the vehicle the player is riding in, but the **value remains 0 and does not change.**
It was the same whether I tried to get it from player.lastvehicle or from player.character.currentvehicle.

### Steps To Reproduce

1. Try to get the steering angle of a vehicle via Vehicle.SteeringAngle
2. Always returns zero.

### The Current Behavior

Even if I get in the car and move the steering wheel left or right, the value remains 0 and does not change.

### The Expected Behavior

I want the value to change when I turn the handle.

**Comment by kagikn** [comment]
Already solved in 893d92d47b8222a70e398dbc8cabc67afe55f12c, so just use a nightly build from [the CI build repo](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases) or wait for v3.7.0.
