### ISSUE TITLE
[Bug]:Failed to create filewatcher.

### ISSUE THREAD

**Issue by clpoz** [scripthookvdotnet/scripthookvdotnet#1429]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

0d5b09b

### Game Version

v1.0.3179

### Bug Description

In the ScriptHookVDotNet.log, these happened.
[22:49:29] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[22:49:29] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[22:49:29] [DEBUG] Initializing NativeMemory members...
[22:49:31] [ERROR] Failed to create filewatcher: System.Reflection.TargetInvocationException: 

[ScriptHookVDotNet.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/15222763/ScriptHookVDotNet.log)
[ScriptHookV.log](https://github.com/scripthookvdotnet/scripthookvdotnet/files/15222766/ScriptHookV.log)

### Steps To Reproduce

1. I paste ScriptHookVDotNet.asi and 2.dll 3.dll to the game folder of GTAV
2. start the game, and it happen as the log file shown

### The Current Behavior

None

### The Expected Behavior

None

**Comment by kagikn** [comment]
`SHVDN.FileWatcher` does not exist in at least the commit 0d5b09b29641ef90e99b4776f76db46c280bd01d. How could be a legitimate issue if the error log stated a class in our module that doesn't actually exist? Period.
