### ISSUE TITLE
[Bug]: Vector3 ForwardVector, UpVector, RightVector Inconsistency

### ISSUE THREAD

**Issue by mbahdokek** [scripthookvdotnet/scripthookvdotnet#1433]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

32e7c01

### Game Version

v1.0.3179.0

### Bug Description

I'm in the process of updating one of Jedijosh920's mods, Shootdodge, which is a mod that incorporates shootdodge max payne-like mechanic to the game. Jedijosh original script uses ApplyForce to the Character, with one of the arguments being the Force. Jedi uses  Vector3 ForwardVector, UpVector, and RightVector for calculating the force (multiplied by the force value) and the orientation.

Unfortunately, in each bug testing session, the force changes in an unexplained way. Sometimes the Char dodges normally, but sometimes it loses force and the trajectory is then reduced by almost half. Running and walking or entity speed, there's velocity calculation being applied but removing still gives no effect. Changing ApplyForce to Native APPLY_FORCE_TO_ENTITY and disabling the ScaleByMass seems to lessen the frequency of it being unpredictable, but still the problem persists. 

The only thing that is consistent throughout the testing is activating it when the player is on top of stairs (not at the end or at the start but at the middle) seems to slows down or cut the force. The rest is always unpredictable
I've peeked at the SHVDN reference, and the UpVector and the rest of it have an IF and fallback to return the value with Vector3.Relative. 
I just need confirmation whether this is a problem on your end to, maybe other devs also have experienced it.

### Steps To Reproduce

Function.Call(Hash.APPLY_FORCE_TO_ENTITY, Game.Player.Character, 1, (forceDirection.X + playerVelocity.X) * 200, (forceDirection.Y + playerVelocity.Y) * 200, (forceDirection.Z + playerVelocity.Z) * 200, 0, 0, 0, 0, false, false, false, false, true);
// 200 is for replacing the ScaleByMass

Determining the forceDirection is handled with (this example for dodging to front):
if (num1 == 0.0f && num2 == -1.0f)
{
  forceDirection = Game.Player.Character.ForwardVector * Configuration.jumpForceForward + Game.Player.Character.UpVector * Configuration.jumpForceUpward;
  Game.Player.Character.Task.PlayAnimation("move_jump", "dive_start_run", 8f, 1f, -1, AnimationFlags.UseFullBlending, 0.0f);
  animName = "dive_start_run";
  
  // num1 and num2 being the MoveLeftRight and UpDown (float num1 = Function.Call<float>(Hash.GET_CONTROL_NORMAL, 2, this being 218 or 219 respectively)
//Configuration.jumpForceForward and jumpForceUpward is inside a config which is set to jumpForceForward = 8.0f;
jumpForceUpward = 2.4f;

I've tried to delete the playerVelocity modifier gives no effect, even originally the playerVelocity is used by Jedi to fill the vOffset and that also gives no effect, still the unpredictable force persists.

### The Current Behavior

Unpredictable force when applying force to entity Game.Player.Character, force can become weaker randomly, the expected trajectory is not up to satisfaction because of the weaker force

### The Expected Behavior

Consistent output so the force being produced is not very random, and only affected by the movement and the velocity of the character entity itself

**Comment by kagikn** [comment]
This is not the place to report if you are suspecting the issue happens because you used some natives wrong. I don't see anything wrong with SHVDN.

You may want to note that;
- `APPLY_FORCE_TO_ENTITY` applies an internal impulse when you pass 1 as the second argument, it applies a constant internal force when you pass 0
- The max linear speed for Entities is at most 500 m/s (but maybe less, I don't remember the exact limit)
- `ForwardVector`, `UpVector`, and `RightVector` fetch the corresponding components of the entity's transform unless SHVDN fails to get the memory address of the entity

**Comment by mbahdokek** [comment]
Ah okay sorry I'm new to scripting mods, and still figuring it out. The usage of 1 is actually what the original mod author used with the ApplyForce, using the MaxForceRot (it's an old mod that uses SHVDN2), also tested the constant one because I already read your explanation on Gta Forum regarding Applying Forces. I kinda just followed the original, but yeah this has been buggin' me, maybe it's just by design that applying force is not that good to be used for this purpose, Thanks for the confirmation tho
