### ISSUE TITLE
Can we have a ScriptHookDotNet for GTA IV?

### ISSUE THREAD

**Issue by ARandom12** [scripthookvdotnet/scripthookvdotnet#1437]
Since GTA5 has the best Script making library. But is it possible to have such for GTA 4 as well? There was one but it's left behind like a dead stuff. There is IVSDK for GTA4, but again it got left dead due to some arguments between the Author of it and other modder who made - FusionFix mod.

**Comment by kagikn** [comment]
Sorry, but I will not integrate ClonkAndre's IV-SDK .NET or GTAIV .Net Script Hook by HarardX into this project. If you came here to ask me to update them for better game support, this is not a place to ask.
