### ISSUE TITLE
We need an update for v1.0.3258.0

### ISSUE THREAD

**Issue by sniky21** [scripthookvdotnet/scripthookvdotnet#1460]
We NEED an update for v1.0.3258.0

**Comment by kagikn** [comment]
Duplicate of *at least* #1454 if you are getting infinite loading screen or game crash even with a nightly version of SHVDN. Duplicate of #1451 if scripts crash with the log file mentions `NativeMemory` in v1.0.3258.0 with only the stable SHVDN build v3.6.0 but not in nightly builds.

**Comment by devyl-90** [comment]
ciao ragazzi anche io ho lo stesso problema..caricamento infinito e non va ho provato vari scripthookdonetnight ma niente qualcuno mi aiuta grazie...
