### ISSUE TITLE
[Bug]:  Script folder not working even using the latest nightly version

### ISSUE THREAD

**Issue by Adam24434** [scripthookvdotnet/scripthookvdotnet#1464]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

ddae3cadb9d30c6d4adb430d0b08f3c0b788336f

### Game Version

v1.3258.0

### Bug Description

Ive tried the suggested method, using the latest nightly version, but my scripts still wont load/being used as it dont exist.

### Steps To Reproduce

1. Download the latest nightly version
2. play gta v

### The Current Behavior

Script not working

### The Expected Behavior

Script working

**Comment by jonjongames1997** [comment]
3528? You mean 3258.

**Comment by Adam24434** [comment]
Yes my mistake. I just noticed the typo in game version

**Comment by kagikn** [comment]
What your ScriptHookVDotNet.log says?

**Comment by Adam24434** [comment]
[19:31:45] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[19:31:45] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[19:31:45] [DEBUG] Initializing NativeMemory members...
[19:31:46] [DEBUG] Loading scripts from C:\Program Files
(x86)\Steam\steamapps\common\Grand Theft Auto V\scripts ...
[19:31:46] [WARNING] Failed to reload scripts because the C:\Program Files
(x86)\Steam\steamapps\common\Grand Theft Auto V\scripts directory is
missing.

**Comment by Adam24434** [comment]
![image](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/84770001/841459e4-6c7b-4cf7-963e-774b8029d302)
im sure i have the script folder

**Comment by kagikn** [comment]
You need to create script*s* folder, not script without the end *s*.

**Comment by Adam24434** [comment]
ok ive noticed something stupid......istg

**Comment by Adam24434** [comment]
thank you for the reply
