### ISSUE TITLE
No me cargan los scripts en el juego, y al usar las versiones nightly me saca del juego y tampoco carga[Bug]: 

### ISSUE THREAD

**Issue by Ligtkino** [scripthookvdotnet/scripthookvdotnet#1482]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

89

### Game Version

1.0.0.66

### Bug Description

Al entrar al juego los scripts no cargan, (ninguno) es decir, nisiquiera aparecen y al presionar f4 el juego se congela y se cierra solo. Con las versiones nightly nisiquiera me deja entrar al juego... ya probé con varias versiones normales y nightly y nada. También la carpeta scripts esta bien nombrada y ya van dos veces que reinstalo el juego y nada.

### Steps To Reproduce

no hay

### Link To Code Example

no hay

### The Current Behavior

No cargan los scripts y se sale al presionar f4

### The Expected Behavior

Que funcionen los scripts y no se salga al presionar f4

**Comment by kagikn** [comment]
I regret to inform you that this issue appears to be duplicate of #1454.

With regard to you speaking Spanish, I am afraid to say that I have spoken Spanish little. If you have more things to inform, I would appreciate it if you spoken to me in English.

**Comment by Ligtkino** [comment]
Yes thank you very much. I just solved the problem using the stable version 3.1.0 and now all my scripts run well and it doesn't crash when trying f4.

**Comment by Ligtkino** [comment]
Yes thank you very much. I just solved the problem using the stable version 3.1.0 and now all my scripts run well and it doesn't crash when trying f4.
