### ISSUE TITLE
[Bug]: Can no longer enable online maps

### ISSUE THREAD

**Issue by JohnFromGWN** [scripthookvdotnet/scripthookvdotnet#1483]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

nightly 115 - don't have game open

### Game Version

3285

### Bug Description

I never use a trainer to enable MP online maps. I use my own scripts using the native function from a menu.
`Function.Call((Hash)0x0888C3502DBBEEF5);`

This works without any issuesl on versions before R* update 3258. Tonight I installed 3285 for testing purposes as well as the  nightly build ScriptHookVDotNet-v3.6.0-nightly.115 as I had read there were problems. 

Anyway, I'm passing this on although I play reverted 99.9% of the time.  (N.B. I don't use Simple Trainer to enable MP online).

### Steps To Reproduce

This code no longer works in V3258 with nightly 115. As a result I can't load MP online maps. For example I normally load Cayo Perico with its IPLs in MP online mode.  However it no longer loads as it requires to online mapping. No error messages, just doesn't load. No run time errors and obviously no compiler error since i've had this script for years.

Code run
`Function.Call((Hash)0x0888C3502DBBEEF5);  `      //void ON_ENTER_MP()

### The Current Behavior

Does nothing.

### The Expected Behavior

Loads MP Online Maps for addons that require it.

**Comment by JohnFromGWN** [comment]
UPDATE:  I swapped in the exe from 3274 and for whatever reasons that fixed the issue. No idea why 3258 was broken.

**Comment by kagikn** [comment]
Can't repro even in b3258 and with `Function.Call(Hash.ON_ENTER_MP)` in my game.
