### ISSUE TITLE
[Bug]: Random Self Radio Game Crash

### ISSUE THREAD

**Issue by JokerOmega1** [scripthookvdotnet/scripthookvdotnet#1484]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### SHVDN Version

nightly.115

### Game Version

v1.0.3274.0

### Bug Description

Upon loading into game and switching to self radio the game will freeze crash at random (only happens some times). It's the same type of freeze crash I was experiencing with the "Crash during game load #1454" issue, where I have to completely reboot the computer, or completely sign out.

### Steps To Reproduce

1. Load into game.
2. Get into a vehicle.
3. Switch to Self Radio.

### The Current Behavior

Game freeze crashes when switching to self radio.

### The Expected Behavior

Switching to self radio should initiate without freeze crashing the game.

**Comment by kagikn** [comment]
I'm afraid to say, but I saw many people (maybe not a lot) saying Self Radio can crash the game *without using SHVDN*. If you could test if your music files can crash the game when using it without SHVDN, I would be convinced that this issue is valid. You may be end up converting them using other formats or stop using Self Radio at all to prevent the game from crashing, however.

**Comment by JokerOmega1** [comment]
I understand, but this has only started happening to me now after the latest update, I have played GTA V pre-update using self radio with the music files I have now (haven't touched them in years) with no issues what so ever. I'll see what happens, but I have a base copy of GTA 5 without mods installed for when I play GTA Online, and I have been playing that a fair bit lately and haven't experienced one Self Radio crash. I don't know, I hope you at least take a look, if not, oh well.

**Comment by nomakewan** [comment]
Self Radio works fine here. 3274, Nightly 115.

![selfradio](https://github.com/user-attachments/assets/310bbff5-dc9d-4031-b9dd-a55b188ef8ea)
