### ISSUE TITLE
[Bug]: Vehicle.Speed fails to work properly when the vehicle is a train

### ISSUE THREAD

**Issue by LeeC2202Git** [scripthookvdotnet/scripthookvdotnet#1487]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

nightly.115

### Game Version

V 1.0.3274.0

### Bug Description

I was trying to convert my train control mod from SHVDN v2 to v3 but I cannot get the train to change speed under script control. I wrote a simple train controller mod and that exhibits the same problem. All I am doing in the simple mod is applying an eased SIN speed value to either brake or accelerate the train after pressing a button. The main train control mod uses speed information stored in the track nodes, so that it can control the AI trains.

The only difference between the v2 and v3 versions is the v3 API specific control, notification and subtitle code. I have attached the v3 class files as a zip file so that you can see what it is doing. The project was created by duplicating the v2 project and then just changing the specific v3 requirements (including reference of course), so the core code is identical in both versions. I can attach the full project if you need it, I just thought the class files would be a good starting point.

The mod was built against v3.6.0 release build but the game runs the nightly build because of the compatibility problems.

[TrainController.zip](https://github.com/user-attachments/files/16534934/TrainController.zip)

### Steps To Reproduce

This is based on those class files to get the train functionality.

Stand next to the train tracks and wait for the freight train to pass. When it gets close, press the vehicle enter control to get into the train. Once inside the train, press Gamepad A (not sure what the keyboard equivalent of that is inside a vehicle) to brake the train and then when it has stopped, press the same control to accelerate it again.

### The Current Behavior

Setting Vehicle.Speed doesn't change the speed of the vehicle when it is a train using the v3 API.

### The Expected Behavior

The train should accelerate and brake as instructed by the code, as it does with the v2 API.

**Comment by kagikn** [comment]
First of all, I must apologize for the inconvenience due to the lack of the upgrade guide. However, since there may be breaking changes between different major versions and how `Entity.Speed` behaves doesn't change since v3.0.0, I do not consider the property has bugs. Use `Vehicle.ForwardSpeed` in the v3 API to achieve what `Vehicle.Speed` does in the v2 API.

As a side note, scripts intended to be open to the public should be built against stable versions, because anything only in nightly versions is subject to change without changing the major version.

**Comment by LeeC2202Git** [comment]
Hmmm... I thought I had tried ForwardSpeed and got the same result but after trying it again, that does seem to work. The problem with ForwardSpeed is that it doesn't have a **_get_** accessor, meaning you are getting the value with Speed and then setting it with ForwardSpeed.

As stated in my original post, the mod _**was**_ built against 3.6.0 stable release build and only tested in-game with the nightly build due to the game version being used.

Thanks for the help.
