### ISSUE TITLE
[Bug]: [ERROR] Failed to instantiate script Main... Illegal call to 'Script.Wait()' outside main loop!

### ISSUE THREAD

**Issue by musabey2000** [scripthookvdotnet/scripthookvdotnet#1494]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

ScriptHookVDotNet-v3.6.0-nightly.119

### Game Version

v1.0.3274.0

### Bug Description

Hello, I have a problem with the game. Every time I enter, it loads and displays as if it is entering online and the game is interrupted. I found this problem and I do not know where to find the code and modify it.
![Grand Theft Auto V 04_09_2024 05_17_56 م](https://github.com/user-attachments/assets/13f50db1-21eb-48e5-b713-947fa432c88b)

### Steps To Reproduce

[Bug]: [ERROR] Failed to instantiate script Main... Illegal call to 'Script.Wait()' outside main loop!

### The Current Behavior

I can't find the script Main... Illegal call to 'Script.Wait()'

### The Expected Behavior

[Bug]: [ERROR] Failed to instantiate script Main... Illegal call to 'Script.Wait()' outside main loop!

**Comment by kagikn** [comment]
Judging from the bug report, it doesn't look like you're not a script developer. Remove scripts one by one and contact the author(s) of faulty scripts if you're not a dev or you're not sure your script is causing the issue.

**Comment by kagikn** [comment]
Don't use `Model.Request` or whatever can indirectly call `Script.Wait` in constructors of classes that inherit `GTA.Script`, because they are instantiated in a thread where `Script.Wait` is not allowed to call. If you have no idea what I'm talking about, find faulty scripts and contact the author(s).

It would be better if you could have clarified whether you code scripts.

**Comment by kagikn** [comment]
It would've been appreciated if you hadn't posted an irrational topic but had posted a bug report with how to reproduce.
