### ISSUE TITLE
[Bug]: Ped.SeeingRange always returns 0

### ISSUE THREAD

**Issue by tp-mods** [scripthookvdotnet/scripthookvdotnet#1495]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

8a2d822

### Game Version

v1.0.3274.0

### Bug Description

The Ped.SeeingRange property no longer works and will always return 0. The setter works fine.

### Steps To Reproduce

1. Try to get the current seeing range of a Ped
2. Always returns 0

### The Current Behavior

Ped.SeeingRange always returns 0.

### The Expected Behavior

Ped.SeeingRange should return the ped's current seeing range.

**Comment by kagikn** [comment]
Confirmed as a bug and reproducible in all game versions.
