### ISSUE TITLE
The old ScriptHookV SDK link is unavailable, making Github Actions builds fail

### ISSUE THREAD

**Issue by nomakewan** [scripthookvdotnet/scripthookvdotnet#1500]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

ca73faf (reproducible after Sep 25, 2024, 6:20 PM UTC at the latest)

### Game Version

v1.0.3337.0

### Bug Description

ScriptHookV went through a major change for v3337 of GTAV, with Alexander Blade mentioning in the changelog:
```
v1.0.3337.0
	- added ability to create ingame UIs using Flutter widgets (see features)
	- added ability to get plain game version info (see main.h)
```
The SDK, likewise, is no longer at the previous SDK link but is rather at `http://dev-c.com/files/ScriptHookV_SDK_1.0.3337.0.zip`. It is not known if this is going to be the permanent future link, or if upon the release of a new version this link will change accordingly with the newer version number.

### Steps To Reproduce

1. Make any commit or PR.
2. Receive error about unavailable SDK in the build failure report on GitHub Actions.

### The Current Behavior

All GitHub Actions builds fail due to unavailable ScriptHookV SDK link.

### The Expected Behavior

Builds succeed if there is no underlying issue with SHVDN's code in the commit.

**Comment by kagikn** [comment]
This is actually a CI build issue. Only the ASI fails to build directly because `install_sdk.ps1` fail to download the SHV SDK. Scripting APIs fail to build only because the ASI doesn't exist after an attempt to build it. Here's where the CI builds fail;

https://github.com/scripthookvdotnet/scripthookvdotnet/blob/ca73fafd808dcc43b42f40a356fcf3c336c23e0e/tools/install_sdk.ps1#L4

I didn't expect this coming, but we need to update the SDK URL to the latest.

**Comment by nomakewan** [comment]
I don't think anyone expected it. This update blindsided a lot of the modding community.

Thanks for looking into it so quickly!

**Comment by kagikn** [comment]
I believe that tilde key assign of SHV is way too an aggressive move for an plugin that introduce custom scripts, but we can just hope AB add the ability to disable in-game options (and an ini file does the job instead) or at least change the key assign...

**Comment by nomakewan** [comment]
I'd honestly prefer if the Flutter functionality was moved into its own separate DLL personally, but agreed.

**Comment by kagikn** [comment]
For those reading this issue, the SDK URL doesn't always change the SDK URL on the web page of Script Hook V every time the Script Hook V author AB releases new versions, but he can change it. Although AB didn't change the SDK link when the first SHV that supports v1.0.3351.0 was released, he changed the *domain* of the SHV binary archive and the SDK archive when the first SHV that supports v1.0.3407.0 was released.
