### ISSUE TITLE
Let scripts continue to execute after calling blocking native funcs for comparibility reasons

### ISSUE THREAD

**Issue by kagikn** [scripthookvdotnet/scripthookvdotnet#1509]
### 📝 Feature Description
Add the ability to prevent scripts from getting aborted for calling a long-blocking native function, so old scripts that are built against v3.6.0 or earlier can run after doing that without chore ***for compatibility reasons***. We could let new scripts continue to run only when they explicitly wish to continue to run after calling a long-blocking native with a new attribute, or when they used some new method (say, like `GTA.Native.Function.CallLongBlockingNativeFuncs`). In short, SHVDN should let scripts that are built against v3.6.0 or earlier continue to run after calling a long-blocking native function, just like how scripts behaved in v3.6.0 and earlier, but it should let scripts that are built v3.7.0 or later continue to run after calling one only when explicitly wish to with a attribute or a special method.

@Tanjitsu pointed out that calling `ON_ENTER_MP` or `ON_ENTER_SP` would abort a script in [v3.6.0-nightly.128](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.128) but it doesn't in the stable v3.6.0 about a week ago, and I consider this a bug.

### 🔧 Feature Workflow
- Add an attribute that determines if script can get aborted for calling a long-blocking native function if not via a special method like `GTA.Native.Function.CallLongBlockingNativeFuncs`. Can get aborted by default for script built against v3.7.0 or later.
- Let scripts that are built v3.6.0 or earlier continue to run after calling a long-blocking native funcs, just like how SHVDN run scripts in v3.6.0 or earlier (***for compatibility reasons!***)

I think I need to refactor how to hold metadata of assemblies and types that are subclass of `GTA.Script` in `ScriptDomain` first, though, so the `ScriptDomain` instance can find the API version associated with a script assembly cheap enough.

**Comment by Tanjitsu** [comment]
Altering the .ini for ScriptTimeoutThreshold to 6000 from 5000 will pass ON_ENTER_MP but this may very much be timing independent depending on machine loading.
