### ISSUE TITLE
add a few more markertypes name to the shv nightly version

### ISSUE THREAD

**Issue by lucienlmy** [scripthookvdotnet/scripthookvdotnet#1513]
Some MarkerType name are missing, starting with DebugSphere, and the ones after that are missing

(https://github.com/scripthookvdotnet/scripthookvdotnet/blob/main/source/scripting_v3/GTA/MarkerType.cs)

	public enum MarkerType
	{
		UpsideDownCone,
		VerticalCylinder,
		ThickChevronUp,
		ThinChevronUp,
		CheckeredFlagRect,
		CheckeredFlagCircle,
		VerticleCircle,
		PlaneModel,
		LostMCDark,
		LostMCLight,
		Number0,
		Number1,
		Number2,
		Number3,
		Number4,
		Number5,
		Number6,
		Number7,
		Number8,
		Number9,
		ChevronUpx1,
		ChevronUpx2,
		ChevronUpx3,
		HorizontalCircleFat,
		ReplayIcon,
		HorizontalCircleSkinny,
		HorizontalCircleSkinnyArrow,
		HorizontalSplitArrowCircle,
		DebugSphere,
		DollarSign,
		HorizontalBars,
		WolfHead,
		QuestionMark,
		PlaneSymbol,
		HelicopterSymbol,
		BoatSymbol,
		CarSymbol,
		MotorcycleSymbol,
		BikeSymbol,
		TruckSymbol,
		ParachuteSymbol,
		Jetpack,
		SawbladeSymbol,
		VerticalCube,
		RadarSymbol,
		Wrench,
	}

**Comment by kagikn** [comment]
It's glad to finally see you creating an issue that would actually improve SHVDN in here. I wonder where all the enums between `DollarSign` and `Wrench` when all the members of the enum `MarkerType_e` are known after that code incident in Dec 2023, though, did they came to your mind? Actual members are;
```cpp
enum MarkerType_e
{
	MARKERTYPE_INVALID					= -1,

	MARKERTYPE_CONE						= 0,
	MARKERTYPE_CYLINDER,
	MARKERTYPE_ARROW,
	MARKERTYPE_ARROW_FLAT,
	MARKERTYPE_FLAG,
	MARKERTYPE_RING_FLAG,
	MARKERTYPE_RING,
	MARKERTYPE_PLANE,
	MARKERTYPE_BIKE_LOGO_1,
	MARKERTYPE_BIKE_LOGO_2,
	MARKERTYPE_NUM_0,
	MARKERTYPE_NUM_1,
	MARKERTYPE_NUM_2,
	MARKERTYPE_NUM_3,
	MARKERTYPE_NUM_4,
	MARKERTYPE_NUM_5,
	MARKERTYPE_NUM_6,
	MARKERTYPE_NUM_7,
	MARKERTYPE_NUM_8,
	MARKERTYPE_NUM_9,
	MARKERTYPE_CHEVRON_1,
	MARKERTYPE_CHEVRON_2,
	MARKERTYPE_CHEVRON_3,
	MARKERTYPE_RING_FLAT,
	MARKERTYPE_LAP,
	MARKERTYPE_HALO,
	MARKERTYPE_HALO_POINT,
	MARKERTYPE_HALO_ROTATE,
	MARKERTYPE_SPHERE,
	MARKERTYPE_MONEY,
	MARKERTYPE_LINES,
	MARKERTYPE_BEAST,
	MARKERTYPE_QUESTION_MARK,
	MARKERTYPE_TRANSFORM_PLANE,
	MARKERTYPE_TRANSFORM_HELICOPTER,
	MARKERTYPE_TRANSFORM_BOAT,
	MARKERTYPE_TRANSFORM_CAR,
	MARKERTYPE_TRANSFORM_BIKE,
	MARKERTYPE_TRANSFORM_PUSH_BIKE,
	MARKERTYPE_TRANSFORM_TRUCK,
	MARKERTYPE_TRANSFORM_PARACHUTE,
	MARKERTYPE_TRANSFORM_THRUSTER,
	MARKERTYPE_WARP,
	MARKERTYPE_BOXES,
	MARKERTYPE_PIT_LANE,

	MARKERTYPE_MAX
};
```
You could create a commit that adds all the members `MARKERTYPE_MONEY` to `MARKERTYPE_PIT_LANE` but without the prefix `MARKERTYPE_` and with the case being Pascal case (e.g. `MARKERTYPE_TRANSFORM_THRUSTER` should be converted into `TransformThruster`), well, if you're happy to create a pull request. You can get more experienced in Git, and I can save a little time. We should ignore `MARKERTYPE_MAX`, because this is not defined for indicies and just a typical Rockstar way to specify a size for a certain array.

You may get surprised, but we can actually see the *actual* prop model names that define marker textures in the exe as **raw** strings, not hashed ones.

**Comment by lucienlmy** [comment]
> 很高兴终于看到你在这里创建了一个可以真正改善 SHVDN 的问题。我想知道在 2023 年 12 月发生那起代码事件之后，枚举的所有成员在何时`DollarSign`以及在何时被人知晓，你想到了吗？实际成员是；`Wrench``MarkerType_e`
> 
> ```c++
> enum MarkerType_e
> {
> 	MARKERTYPE_INVALID					= -1,
> 
> 	MARKERTYPE_CONE						= 0,
> 	MARKERTYPE_CYLINDER,
> 	MARKERTYPE_ARROW,
> 	MARKERTYPE_ARROW_FLAT,
> 	MARKERTYPE_FLAG,
> 	MARKERTYPE_RING_FLAG,
> 	MARKERTYPE_RING,
> 	MARKERTYPE_PLANE,
> 	MARKERTYPE_BIKE_LOGO_1,
> 	MARKERTYPE_BIKE_LOGO_2,
> 	MARKERTYPE_NUM_0,
> 	MARKERTYPE_NUM_1,
> 	MARKERTYPE_NUM_2,
> 	MARKERTYPE_NUM_3,
> 	MARKERTYPE_NUM_4,
> 	MARKERTYPE_NUM_5,
> 	MARKERTYPE_NUM_6,
> 	MARKERTYPE_NUM_7,
> 	MARKERTYPE_NUM_8,
> 	MARKERTYPE_NUM_9,
> 	MARKERTYPE_CHEVRON_1,
> 	MARKERTYPE_CHEVRON_2,
> 	MARKERTYPE_CHEVRON_3,
> 	MARKERTYPE_RING_FLAT,
> 	MARKERTYPE_LAP,
> 	MARKERTYPE_HALO,
> 	MARKERTYPE_HALO_POINT,
> 	MARKERTYPE_HALO_ROTATE,
> 	MARKERTYPE_SPHERE,
> 	MARKERTYPE_MONEY,
> 	MARKERTYPE_LINES,
> 	MARKERTYPE_BEAST,
> 	MARKERTYPE_QUESTION_MARK,
> 	MARKERTYPE_TRANSFORM_PLANE,
> 	MARKERTYPE_TRANSFORM_HELICOPTER,
> 	MARKERTYPE_TRANSFORM_BOAT,
> 	MARKERTYPE_TRANSFORM_CAR,
> 	MARKERTYPE_TRANSFORM_BIKE,
> 	MARKERTYPE_TRANSFORM_PUSH_BIKE,
> 	MARKERTYPE_TRANSFORM_TRUCK,
> 	MARKERTYPE_TRANSFORM_PARACHUTE,
> 	MARKERTYPE_TRANSFORM_THRUSTER,
> 	MARKERTYPE_WARP,
> 	MARKERTYPE_BOXES,
> 	MARKERTYPE_PIT_LANE,
> 
> 	MARKERTYPE_MAX
> };
> ```
> 
> 您可以创建一个提交，将所有成员添加`MARKERTYPE_MONEY`到`MARKERTYPE_PIT_LANE`，但不带前缀`MARKERTYPE_`，大小写为 Pascal 大小写（例如，`MARKERTYPE_TRANSFORM_THRUSTER`应转换为`TransformThruster`），如果您愿意创建拉取请求。您可以在 Git 中获得更多经验，我可以节省一点时间。我们应该忽略`MARKERTYPE_MAX`，因为这不是为索引定义的，只是 Rockstar 为特定数组指定大小的典型方法。
> 
> 您可能会感到惊讶，但我们实际上可以看到在 exe 中定义标记纹理的_实际道具模型名称是_**原始**字符串，而不是散列字符串。

I don't know why I can't create PR，It is gray.What do you mean by the code event in December 2023

**Comment by kagikn** [comment]
The code event in December 2023 means the source code leak of the game. I'm afraid to say that I'm not really sure what you mean by "it is gray" of your statement "I don't know why I can't create PR，It is gray", but maybe [an article about how to create a PR on GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?platform=windows) helps.

**Comment by lucienlmy** [comment]
> The code event in December 2023 means the source code leak of the game. I'm afraid to say that I'm not really sure what you mean by "it is gray" of your statement "I don't know why I can't create PR，It is gray", but maybe [an article about how to create a PR on GitHub Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?platform=windows) helps.

It's better for you to modify it. To be honest, I don't quite understand how to add markup code. My original intention was to directly modify the code here〔https://github.com/scripthookvdotnet/scripthookvdotnet/blob/main/source/scripting_v3/GTA/MarkerType.cs〕, just add it laterBut I still haven't understood the method you mentioned through translation software

**Comment by kagikn** [comment]
Fair enough, I'll add missing members. Will add canonical names for the values existing members are taking places and mark the old ones as obsolete, though.
