### ISSUE TITLE
3.6.0 Nightly 142 and higher are unable to run LemonUI

### ISSUE THREAD

**Issue by justalemon** [scripthookvdotnet/scripthookvdotnet#1520]
### 📦 What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### 🛠️ SHVDN Version

v3.6.0-nightly.142

### 🎮 Game Version

2944, 3095, 3258, 3274 and more

### 🐛 Bug Description

Nightly versions starting from 3.6.0 142 and higher make LemonUI no longer load, even with no other mods present.

The log files will look like this:

```
[17:07:39] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[17:07:39] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[17:07:39] [DEBUG] Initializing NativeMemory members...
[17:07:40] [DEBUG] Loading scripts from D:\Games\EPIC\GTAV\scripts ...
[17:07:40] [DEBUG] Loading assembly LemonUI.SHVDN3.dll ...
```

With no crash reason after that.

### 🔄 Steps To Reproduce

1. Install SHVDN Nightly 3.6.0 142 or higher
2. Install LemonUI
3. Launch the game

### ⚠️ Current Behavior

Game crashes

### 🎯 Expected Behavior

Game does not crashes, just like versions 3.6.0 141 and older.

**Comment by kagikn** [comment]
Even though the exe wants to kill itself whenever it find itself attached by a debugger by occasional checks (like every time 20 seconds), I found the cause in about 10 minutes. Another moment where the debugger helped me find the cause 😛
