### ISSUE TITLE
[Bug]: Github Action for testing SHV SDK is broken

### ISSUE THREAD

**Issue by nomakewan** [scripthookvdotnet/scripthookvdotnet#1526]
### 📦 What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime), ScriptHookVDotNet3.dll (v3 SDK/API), ScriptHookVDotNet2.dll (v2 SDK/API)

### 🛠️ SHVDN Version

Nightly

### 🎮 Game Version

v1.0.3407.0

### 🐛 Bug Description

The github action that was implemented to automatically check to see if the URL for the ScriptHookV SDK has been altered and open an issue if so does not work. This can be seen because the compile check for PR #1525 has failed due to the SDK URL having been altered, and yet the action--despite correctly returning a 404!--failed to create a new issue which can be seen [here](https://github.com/scripthookvdotnet/scripthookvdotnet/actions/runs/12307747557/job/34351957026).

The action's inability to correctly open a new issue when the URL changes should be corrected, and likewise the URL for the SHV SDK should be updated.

### 🔄 Steps To Reproduce

1. Run the `Create issue if URL of SHV SDK returns status code 404 (Not Found)` action.
2. See that it returns 404 but fails to open a new issue alerting the maintainer to this fact.

### ⚠️ Current Behavior

Action correctly detects a 404 condition but fails to create a new issue.

### 🎯 Expected Behavior

Action correctly detects a 404 condition and automatically creates a new issue to alert the maintainer to the problem.

**Comment by kagikn** [comment]
This is responsible to me after all until now, but I'm starting to think that we could avoid our good-old bug label for CI issues. Since this issue is completely not relevant to project bugs, let's avoid using the bug label.

**Comment by nomakewan** [comment]
Agreed; thanks for the new tag, and for the swift fixes!
