### ISSUE TITLE
Has GTA.Global(int index) been deprecated or removed in 2.10.8?

### ISSUE THREAD

**Issue by LeeC2202** [scripthookvdotnet/scripthookvdotnet#825]
There was a post on 5Mods by Mafins about using GTA.Global to deactivate the vehicle despawning.  https://forums.gta5-mods.com/post/136651

But when I try to use the code, I get the error 'Global' does not contain a constructor that takes 1 arguments.

In the devV2 source I have on my PC, it says this:

	Global::Global(int index) : mAddress(getGlobalPtr(index))
	{
	}

Which does seem to indicate that there was once a Global() constructor that did take 1 argument. Does that not exist now, or am I missing something blindingly obvious? I didn't even know you could access the global variables through SHVDN, so this is just a curiosity question more than anything.

**Comment by qiangqiang101** [comment]
me too having this problem
