### ISSUE TITLE
How to get the return type of OutputArgument?

### ISSUE THREAD

**Issue by Hanashi** [scripthookvdotnet/scripthookvdotnet#992]
I tried to execute the following code:
```C#
OutputArgument out = new OutputArgument();
Function.Call(Hash.GET_SHOP_PED_QUERY_OUTFIT, 1, out);
```
Now I don't know what the type of the output is. I tried following `out.GetResult<dynamic>()`, but this crashs the game. I tried all typical types (int, string, ...), but the game crashs or I get the exception `InvalidCastException`. Than I tried create a struct ([source from here](https://gist.github.com/root-cause/e77c1b1e003402687291ea76b0187677)) and tested it as type, but still the exception `InvalidCastException`.

How can I get the correct type for this method?

**Comment by RelaperCrystal** [comment]
SHVDN don't support structures with natives.

**Comment by E66666666** [comment]
You can use SHV's functions directly and pass your structs that way:

[Here's an example for `GET_PED_HEAD_BLEND_DATA`](https://gist.github.com/E66666666/466c59df7aff69d2ac788fa38e669300).

**Comment by Sardelka9515** [comment]
First you need to define the native struct, much like win32 P/Invoke, but `OutputArgument` [only allocate 24 bytes](https://github.com/crosire/scripthookvdotnet/blob/712bad29175b0bd50e2d9ae7c12086c0ec6801e8/source/scripting_v3/GTA.Native/Native.cs#L301). You need to use unsafe code and pass the pointer directly if you have a struct larger than it, otherwise crash is expected.

for example:
```
[StructLayout(LayoutKind.Explicit, Size = 80)]
public struct HeadBlendData
{
	[FieldOffset(0)]
	public int ShapeFirst;

	[FieldOffset(8)]
	public int ShapeSecond;

	[FieldOffset(16)]
	public int ShapeThird;

	[FieldOffset(24)]
	public int SkinFirst;

	[FieldOffset(32)]
	public int SkinSecond;

	[FieldOffset(40)]
	public int SkinThird;

	[FieldOffset(48)]
	public float ShapeMix;

	[FieldOffset(56)]
	public float SkinMix;

	[FieldOffset(64)]
	public float ThirdMix;
}

public static HeadBlendData GetHeadBlendData(Ped ped)
{
	var hbd = new HeadBlendData() {ShapeFirst = -1};
	if(Function.Call<bool>(Hash.GET_PED_HEAD_BLEND_DATA, ped.Handle, (IntPtr)(&hbd)))
	{
		return hbd;
	}
	throw new Exception("GET_PED_HEAD_BLEND_DATA failed");
}
```

**Comment by kagikn** [comment]
Closing this as #1260 makes it able to fetch data via native functions without having to call some of methods in `Marshal` class anymore, like `AllocCoTaskMem` and `PtrToStructure` (and probably `SizeOf`).

Example:
```
// you need to allocate at least 0x4C byte to make sure stack corruption won't happen
// as the last field will be written as a 4-byte value
[StructLayout(LayoutKind.Explicit, Size = 0x50)]
public struct HeadBlendData
{
    /// <summary>
    /// index of head of first parent (same as you would set with a component variation)
    /// </summary>
    [FieldOffset(0)]
    public int Head0;
    /// <summary>
    /// index of head of second parent
    /// </summary>
    [FieldOffset(0x8)]
    public int Head1;
    /// <summary>
    /// index of head used for minor genetic variation
    /// </summary>
    [FieldOffset(0x10)]
    public int Head2;

    [FieldOffset(0x18)]
    /// <summary>
    /// index of texture used for first parent (same as you would set with a component variation)
    /// </summary>
    public int Tex0;
    [FieldOffset(0x20)]
    /// <summary>
    /// index of texture used for second parent
    /// </summary>
    public int Tex1;
    /// <summary>
    /// index of texture used for genetic variation
    /// </summary>
    [FieldOffset(0x28)]
    public int Tex2;

    [FieldOffset(0x30)]
    /// <summary>
    /// the amount of blend between the two parent heads. 0.0 will be fully head0, 1.0 fully head1 and 0.5 will bea 50/50 mix between them
    /// </summary>
    public float HeadBlend;
    [FieldOffset(0x38)]
    /// <summary>
    /// same as headBlend only for the textures
    /// </summary>
    public float TexBlend;
    [FieldOffset(0x40)]
    /// <summary>
    /// the amount of genetic variation applied. 0.0 is no variation and 1.0 will completely replace the parents with the third head. very small values should be used for this.
    /// </summary>
    public float VarBlend;

    // surprisingly, the game reads the "is parent" value a 1-byte value somewhere like "movzx eax, byte ptr [r8+13Dh]"
    // and writes the result as a 4 byte value, like "mov [rbx+48h], eax"
    [FieldOffset(0x48)]
    [MarshalAs(UnmanagedType.I1)]
    public bool IsParent;
}

// returns false if the head blend data is not initalized
public static bool GetHeadBlendData(Ped ped, out HeadBlendData headBlendData)
{
    headBlendData = default;
    OutputArgument outArg = OutputArgument.AllocForStcuct<HeadBlendData>();

    if(Function.Call<bool>(Hash.GET_PED_HEAD_BLEND_DATA, ped.Handle, (outArg))
    {
        headBlendData = outArg.GetResultAsBittableStruct<HeadBlendData>();
        return true;
    }
    return false;
}
```

**Comment by Tanjitsu** [comment]
Sorry to bring up old closed issues but...

Since we have to Set before we can Get
This is then just becomes storage for something we applied values too.
Which seems pointless because I can create and store a local value easily.

The Get would be make sense if we can get the existing values... rather than just override them.
Is an actual Get not possible ?

**Comment by kagikn** [comment]
> Sorry to bring up old closed issues but...
> 
> Since we have to Set before we can Get This is just storage for a value we create, which seems pointless.
> 
> The Get would make sense if we can get the existing values... rather than just override them. Is an actual Get not possible ?

If only your script sets a ped head blend data to some ped, I would say yeah, pointless to call `GET_PED_HEAD_BLEND_DATA`. It requires the ped's `fwExtensionList` to have a `CPedHeadBlendData` referemce before it can return true and the registered blend data. You can also get a blend data registered via another script with that native, though.

**Comment by Tanjitsu** [comment]
Yeah that is true!
